# Generated by Codex on 2026-09-04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wireguard_tools', '0003_alter_emailsettings_smtp_encryption'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=150)),
                ('action', models.CharField(choices=[('peer_created', 'Peer created'), ('peer_updated', 'Peer updated'), ('peer_deleted', 'Peer deleted'), ('peer_suspended', 'Peer suspended'), ('peer_reactivated', 'Peer reactivated'), ('peer_suspend_schedule_updated', 'Peer suspend schedule updated'), ('peer_suspend_schedule_cleared', 'Peer suspend schedule cleared'), ('peer_schedule_profile_updated', 'Peer schedule profile updated'), ('peer_ip_added', 'Peer IP added'), ('peer_ip_updated', 'Peer IP updated'), ('peer_ip_deleted', 'Peer IP deleted'), ('peer_route_template_applied', 'Peer route template applied'), ('peer_route_template_unlinked', 'Peer route template unlinked'), ('wireguard_config_exported', 'WireGuard config exported'), ('wireguard_reloaded', 'WireGuard reloaded'), ('wireguard_restarted', 'WireGuard restarted'), ('wireguard_reload_failed', 'WireGuard reload failed'), ('wireguard_restart_failed', 'WireGuard restart failed')], max_length=64)),
                ('object_type', models.CharField(blank=True, max_length=64)),
                ('object_uuid', models.CharField(blank=True, max_length=64)),
                ('object_name', models.CharField(blank=True, max_length=255)),
                ('wireguard_instance', models.CharField(blank=True, max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['created'], name='wireguard_t_created_777495_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action'], name='wireguard_t_action_16913b_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['username'], name='wireguard_t_usernam_11a996_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['object_type', 'object_uuid'], name='wireguard_t_object__1c821a_idx'),
        ),
    ]
