# Generated by Codex on 2026-09-04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wireguard', '0026_webadminsettings_db_patch_version'),
        ('wireguard_tools', '0004_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('peer_created', 'Peer created'), ('peer_updated', 'Peer updated'), ('peer_deleted', 'Peer deleted'), ('peer_suspended', 'Peer suspended'), ('peer_reactivated', 'Peer reactivated'), ('peer_suspend_schedule_updated', 'Peer suspend schedule updated'), ('peer_suspend_schedule_cleared', 'Peer suspend schedule cleared'), ('peer_schedule_profile_updated', 'Peer schedule profile updated'), ('peer_ip_added', 'Peer IP added'), ('peer_ip_updated', 'Peer IP updated'), ('peer_ip_deleted', 'Peer IP deleted'), ('peer_route_template_applied', 'Peer route template applied'), ('peer_route_template_unlinked', 'Peer route template unlinked'), ('peer_connected', 'Peer connected'), ('peer_disconnected', 'Peer disconnected'), ('peer_handshake_updated', 'Peer handshake updated'), ('wireguard_config_exported', 'WireGuard config exported'), ('wireguard_reloaded', 'WireGuard reloaded'), ('wireguard_restarted', 'WireGuard restarted'), ('wireguard_reload_failed', 'WireGuard reload failed'), ('wireguard_restart_failed', 'WireGuard restart failed')], max_length=64),
        ),
        migrations.CreateModel(
            name='PeerConnectionState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_connected', models.BooleanField(default=False)),
                ('last_handshake', models.DateTimeField(blank=True, null=True)),
                ('transfer_rx', models.BigIntegerField(default=0)),
                ('transfer_tx', models.BigIntegerField(default=0)),
                ('last_event_at', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('peer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='connection_state', to='wireguard.peer')),
            ],
        ),
        migrations.AddIndex(
            model_name='peerconnectionstate',
            index=models.Index(fields=['is_connected'], name='wireguard_t_is_conn_7b970c_idx'),
        ),
        migrations.AddIndex(
            model_name='peerconnectionstate',
            index=models.Index(fields=['last_handshake'], name='wireguard_t_last_ha_26034c_idx'),
        ),
    ]
