# Generated by Django 5.2.12 on 2026-09-11 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0010_add_vpn_user_level_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermfasettings',
            name='reset_allowed',
            field=models.BooleanField(default=False),
        ),
    ]
