# Generated by Django 5.2.12 on 2026-09-12 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0011_usermfasettings_reset_allowed'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermfasettings',
            name='trusted_browser_registered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usermfasettings',
            name='trusted_browser_token_hash',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='usermfasettings',
            name='trusted_browser_user_agent',
            field=models.TextField(blank=True),
        ),
    ]
