# Generated by Django 5.2.12 on 2026-09-12 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wireguard', '0038_peer_mfa_lock_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='peer',
            name='mfa_trusted_browser_required',
            field=models.BooleanField(default=False),
        ),
    ]
